const express = require('express');
const mongoose = require('mongoose');
const bodyParser = require('body-parser');
const path = require('path');
const items = require('./routes/api/items');
const static = require('./routes/api/static');
const networks = require('./routes/api/networks');
//const layers = require('./routes/api/layers');



const app = express();

//bodyparser
app.use(bodyParser.json());

//DB config
const db = require('./config/keys').mongoURI;

// Connect to Mongo

mongoose
    .connect(db)
    .then(() => console.log('Connected to Database'))
    .catch(err => console.log((err)));

//Use Routes

app.use('/api/items', items);
app.use('/api/static', static);
app.use('/api/networks', networks);

//Served compiled static React content in production
if (process.env.NODE_ENV === 'production') {
    //serve static files generated by React
    app.use(express.static('client/build'));

    app.get('*', (req, res) => {
        res.sendFile(path.resolve(__dirname, 'client', 'build', 'index.html'));
    });
}

const port = process.env.PORT || 5000;


app.listen(port, () => console.log(`Server started on port ${port}`));

